[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pact = "HBSRo9sKjWmqTteMRPjVF2xcqratjhF5Hu5GozqctNA4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/icarus/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
